org.gradle.jvmargs=-Xmx4096M
android.useAndroidX=true
android.enableJetifier=true
android.compileOptions.sourceCompatibility=17
android.compileOptions.targetCompatibility=17
android.defaults.namespaceEnabled=true
android.jetifier.ignorelist=androidx/core/view/ViewCompat;androidx/core/widget/NestedScrollView
